### ISSUE TITLE
User-can-search-for-hotels

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/final-project#1]
## 💰 Feature

User can search for 5-star hotels worldwide using city name

## 🗒️ Notes

This will require me to create a component that will fetch and display API data properly
## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/64397693/103145141-ee0bb100-46e9-11eb-8d3d-2c8a95e8e9d5.png)

![image](https://user-images.githubusercontent.com/64397693/103145137-e64c0c80-46e9-11eb-9199-50b79295aeea.png)

## ✅ Tasks

- [x] Define a component that renders the screen as shown in the wireframe, but with no behavior.
- [x] Choose a nice background, place search form on top of background image. 
- [x] Create an input search form via BootStrap
- [x] handle user input in the form properly through the "handleUserInput" method
- [x] Make sure the form is centered and is mobile responsive 
- [x] Set the state with properties to handle user interaction
- [x] handle any client errors (empty inputs, number inputs) inside "handleSearchClick" before calling the fetch function
- [x] Set up "handleSearchClick" method to fetch the appropriate user search request
- [x] extract data from the fetch call and set State so that it includes hotel names + hotel  main pictures
- [x] handle fetch errors asynchronously via promises
- [x] render the hotel name and pictures properly with keys, set as hidden initially.
- [x] add a spinning loader to display while fetch() is running via Bootstrap and conditional rendering in React
- [x] make sure the loader stops once fetch ran successfully
- [x] Use view swapping to hide background and search form but display the hotel names and pictures after fetch() ran successfully
- [x] Create a "back to search screen" arrow so that the user can click it to go back to the search page
- [x] When user clicks on the arrow, setState back to default values (search page becomes visible, result list cleared and hidden
- [x] Clean up all CSS, 
- [x] test all functionalities again, making sure there are no console errors
- [x] test for mobile responsiveness again on iPhones 6/7/8/X, iPad, and iPad Pro
