### ISSUE TITLE
User-can-see-hotel-amenities

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/final-project#2]
## 💰 Feature
Users can see each hotels amenities, such as pools, dining, and entertainment options

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/64397693/103029619-096e9480-450f-11eb-8030-1c7acca901da.png)

## ✅ Tasks

- [x] render a front-end component that matches the Wireframe with no functionality
- [x] use the fetch function to make proper API calls 
- [x] When user clicks on a desired hotel, this new component page should render
- [x] Display the chosen hotel name, thumbnail, and star rating on the header
- [x] Create an accordion-like display under the header which includes titles such as "Dining & Entertainment",  "policies", "amenities", "see review"
- [x] When clicked on, these titles should display their text content beneath them, reclicking the title will hide the text
- [x] test all functionality
- [x] refactor CSS if needed
- [x] create 3 different routes for "search" , "searchResults", and "hotelDetails"
- [x] create nested fetch calls using Node Fetch to send 2 API requests 
- [x] remove all height vh properties in CSS
- [x] Use Bootstrap class helpers wherever appropriate 
- [x] separate components so that each one only does its specific functionality
- [x] check functionality, remove unnecessary code
- [x] extract property data details from the specific hotel that user clicked
