### ISSUE TITLE
User-can-favorite-their-hotels

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/final-project#3]
## 💰 Feature
User Can favorite hotels and add it to the database

## 🗒️ Notes

This will require me to create an Express back-end route to handle HTTP GET requests at `/api/hotels/search`

## 🖼 Wireframe

![image](https://user-images.githubusercontent.com/64397693/103676916-86016a00-4f36-11eb-88dc-1d591a68ed4a.png)

## ✅ Tasks

- [x] add a heart icon next to the Hotel name on the hotelDetails component
- [x] When the user clicks, they will be notified that this certain hotel is added to their list
- [x] create a link to the Favorite tabs when the user clicks the heart icon on the nav bar
- [x] insert a new table to the database with columns "favorites" and "userId"
- [x] create a backend route so that when the user clicks the fav button, their desired hotel is inserted into the database then state is updated
- [x] test the database via HTTpie post request to make sure hotels get added to the database
- [x] test on the front end, hotel ID should be added to the database after user clicks heart icon
