### ISSUE TITLE
User-can-view-and-remove-favorited-hotels

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/final-project#4]
## 💰 Feature
Users can see favorited hotels and click trash icon to remove each one

## 🖼 Wireframe
![image](https://user-images.githubusercontent.com/64397693/103029359-80575d80-450e-11eb-8e12-131d4e684684.png)

## ✅ Tasks

- [x] add an additional fetch call in the backend to get the hotel's name with the provided ID
- [x] create a non functional front-end component resembling the wireframe's favorites tab
- [x] when the favorites component is rendered, a fetch call will be made to the server in order to grab the hotel names from data base
- [x] display hotel names from database in the front-end favorites component
- [x] test functionality
- [x] add trash can icons next to each hotel name in the favorites component
- [x] add functionality to the trash icons so that clicking them will remove the name (and icon) from the screen
