### ISSUE TITLE
User-can-sign-up

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/final-project#5]
## 💰 Feature
Users can create an account by filling in their full name, user name, email, and password

## ✅ Tasks

- [x] create a landing page with a sign up form
- [x] form should have input fields for full name, user name, email, and password
- [x] make sure all fields are required and cannot be left blank, throw user error otherwise
- [x] handle any server-side errors 
- [x] create a backend server route to handle the user's registration (POST request) and add it to the database
- [x] make sure the user's password is hashed and stored in the database by using Argon2
- [x] test functionality, refactor where needed
