### ISSUE TITLE
User-can-log-in

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/final-project#6]
## 💰 Feature

User can sign into their account after creating it

## ✅ Tasks
- [x]  Create front-end component
- [x]  Create back-end route to handle post request
- [x]  handle any server side errors
- [x]  Test to make sure each user can log in correctly
- [x]  Refactor code if needed
- [x]  test functionality once again
