### ISSUE TITLE
User-can-see-a-hotels-reviews

### ISSUE THREAD

**Issue by PhillipLam89** [PhillipLam89/final-project#7]
## 💰 Feature
Users can now sort results by hotel ratings

## 🖼 Wireframe
![image](https://user-images.githubusercontent.com/64397693/104063968-f49e2c00-51b1-11eb-9ca5-9cd3d95a9fb6.png)

## ✅ Tasks

- [x] create a reviews.jsx component
- [x] do a fetch call inside componentDidMount method passing in the hotelId
- [x] create a server route in the back end to retrieve review data from API
- [x] handle any server side errors
- [x] conditionally render the review data with author name included.
- [ ] reviews without a body or author should not display
- [ ] check functionality
- [ ] refactor code when possible
- [ ] test everything again
